version: '3'
services:
  web_container:
    build: Project/.
    image: web_image
    restart: always
    ports:
    - "80:80"
    links:
    - db_container
    depends_on:
      - db_container
  db_container:
    image: mongo
    restart: always
    environment:
    - MONGO_DATA_DIR=/data/db
    - MONGO_INITDB_ROOT_USERNAME=bolao_user
    - MONGO_INITDB_ROOT_PASSWORD=bolao_pass
    expose:
    - "27017"
    volumes:
    - /home/ec2-user/bolao/db:/data/db

    
# run this compose with:
# 
# cd /home/ec2-user/bolao/src
# docker-compose up -d
#
# usefull commands:
#
# docker-compose stop                                   ->  Stop all containers
# docker-compose rm                                     ->  Delete all containers
# docker-compose ps                                     ->  See which containers are running
# 
# docker system prune --all --volumes --force           ->  Delete EVERYTHING: containers, networks, etc
#

